### ISSUE TITLE
Installing and running example from README causes error

### ISSUE THREAD

**Issue by Ghostavio** [pixijs/pixi-react#614]
```
[vite] Internal server error: Cannot find module '/my/path/node_modules/react-reconciler/constants' imported from /my/path/node_modules/@pixi/react/lib/core/createRoot.mjs
Did you mean to import "react-reconciler/constants.js"?
      at finalizeResolution (node:internal/modules/esm/resolve:274:11)
      at moduleResolve (node:internal/modules/esm/resolve:859:10)
      at defaultResolve (node:internal/modules/esm/resolve:983:11)
      at nextResolve (node:internal/modules/esm/hooks:748:28)
      at o (file:///Users/admin/webapps/carney/CC-website/client/node_modules/@tailwindcss/node/dist/esm-cache.loader.mjs:1:69)
      at nextResolve (node:internal/modules/esm/hooks:748:28)
      at o (file:///Users/admin/webapps/carney/CC-website/client/node_modules/@tailwindcss/node/dist/esm-cache.loader.mjs:1:69)
      at nextResolve (node:internal/modules/esm/hooks:748:28)
      at Hooks.resolve (node:internal/modules/esm/hooks:240:30)
      at handleMessage (node:internal/modules/esm/worker:199:24) (x3)
```

This is the code:
```
import { Application, extend } from "@pixi/react"
import { Container, Graphics } from "pixi.js"
import { useCallback } from "react"

extend({
  Container,
  Graphics,
})

const AlternatingVideo = () => {
  const drawCallback = useCallback((graphics) => {
    graphics.clear()
    graphics.setFillStyle({ color: "red" })
    graphics.rect(0, 0, 100, 100)
    graphics.fill()
  }, [])

  return (
    <Application>
      <pixiContainer x={100} y={100}>
        <pixiGraphics draw={drawCallback} />
      </pixiContainer>
    </Application>
  )
}

export default AlternatingVideo
```

Running latest versions of pixi.js (8.10.1) and @pixi/react (8.0.2)

**Comment by thejustinwalsh** [comment]
Hey @Ghostavio that error looks related to your setup and environment that you are running in. Can you please share more details or provide the repo that is using @pixi/react. I am using @pixi/react 8.0.2 in vite without issue personally, and can not reproduce this issue.

**Comment by thejustinwalsh** [comment]
Please send a repo over that has the issue so I can pull and debug it. I believe there is a conflict with the configuration of the project.

**Comment by datacurse** [comment]
same issue here

**Comment by trezy** [comment]
This issue should be resolved in v8.0.3.

**Comment by wahaj-47** [comment]
Issue still exists in v8.0.3
Except it's complaining about the store.mjs file 

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'path\node_modules\react-reconciler\constants' imported from path\node_modules\@pixi\react\lib\store.mjs
Did you mean to import "react-reconciler/constants.js"?
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at o (file:///path/node_modules/@tailwindcss/node/dist/esm-cache.loader.mjs:1:69)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:240:30)
    at handleMessage (node:internal/modules/esm/worker:199:24)
    at Immediate.checkForMessages [as _onImmediate] (node:internal/modules/esm/worker:141:28)
    at process.processImmediate (node:internal/timers:485:21)
```
Adding the .js extension in store.mjs makes it complain about resolveUpdatePriority.mjs

```Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'path\node_modules\react-reconciler\constants' imported from path\node_modules\@pixi\react\lib\helpers\resolveUpdatePriority.mjs
Did you mean to import "react-reconciler/constants.js"?
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at o (file:///path/node_modules/@tailwindcss/node/dist/esm-cache.loader.mjs:1:69)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:240:30)
    at handleMessage (node:internal/modules/esm/worker:199:24)
    at Immediate.checkForMessages [as _onImmediate] (node:internal/modules/esm/worker:141:28)
    at process.processImmediate (node:internal/timers:485:21)
```

I am using the react-router [node-custom-server](https://github.com/remix-run/react-router-templates/tree/main/node-custom-server) template

**Comment by connect-kai** [comment]
+1
